import { useEffect, useState } from "react";
import { ChakraProvider } from "@chakra-ui/react";
import Head from "next/head";
import { SessionProvider } from "next-auth/react";

export default function App({
  Component,
  pageProps: { session, ...pageProps },
}: any) {
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(typeof window !== "undefined");
  }, []);
  return (
    <SessionProvider session={session}>
      <ChakraProvider>
        <Head>
          <title>DEMO</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {isClient && <Component {...pageProps} />}
      </ChakraProvider>
    </SessionProvider>
  );
}
